# https://github.com/kubeflow/pipelines/blob/74c7773ca40decfd0d4ed40dc93a6af591bbc190/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  template:
    spec:
      containers:
      - name: profile-controller
        # envFrom:
        # - configMapRef:
        #     name: kubeflow-pipelines-profile-controller-env
        # env:
        # - name: VISUALIZATION_SERVER_IMAGE
        #   value: "gcr.oneitfarm.com/ml-pipeline/visualization-server"
        # - name: FRONTEND_IMAGE
        #   value: "gcr.oneitfarm.com/ml-pipeline/frontend"
        # - name: KFP_VERSION
        #   valueFrom:
        #     configMapKeyRef:
        #       name: pipeline-install-config
        #       key: appVersion
        # - name: MINIO_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: mlpipeline-minio-artifact
        #       key: accesskey
        # - name: MINIO_SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: mlpipeline-minio-artifact
        #       key: secretkey
        volumes:
        - configMap:
            defaultMode: 420
            name: kubeflow-pipelines-profile-controller-code-overwrite
          name: hooks