apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: katib-ui
          env:
          - name: APP_SECURE_COOKIES
            value: "false"
                